/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/

package com.sample11.services.thom;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2017-12-13T09:28:17.469Z
 * Generated source version: 2.7.11
 * 
 */
public final class BLZServicePortType_BLZServiceSOAP12PortHttp_Client {

    private static final QName SERVICE_NAME = new QName("http://thomas-bayer.com/blz/", "BLZService");

    private BLZServicePortType_BLZServiceSOAP12PortHttp_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = BLZService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        BLZService ss = new BLZService(wsdlURL, SERVICE_NAME);
        BLZServicePortType port = ss.getBLZServiceSOAP12PortHttp();  
        
        {
        System.out.println("Invoking getBank...");
        com.sample11.services.thom.GetBankType _getBank_parameters = null;
        com.sample11.services.thom.GetBankResponseType _getBank__return = port.getBank(_getBank_parameters);
        System.out.println("getBank.result=" + _getBank__return);


        }

        System.exit(0);
    }

}
