/**This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

package com.sample11.services.thom.services;
import com.sample11.services.thom.*;
import java.util.List;

import com.wavemaker.runtime.soap.util.SoapSettingsResolver;
import com.wavemaker.runtime.soap.SoapServiceSettings;

import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import javax.xml.ws.BindingProvider;



@Service
public class ThomService{

    @Autowired
    @Qualifier("thomSoapServiceSettings")
    private SoapServiceSettings soapServiceSettings;


	public GetBankResponseType getBank(  com.sample11.services.thom.GetBankType parameters )
	          {
 	    BLZService blzservice = new BLZService();
 BLZServicePortType blzserviceporttype = blzservice.getBLZServiceSOAP11PortHttp();
 SoapSettingsResolver.setBindingProperties((BindingProvider)blzserviceporttype, soapServiceSettings);
 return blzserviceporttype.getBank(parameters );
	}
}
