/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.sample11.services.test;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2017-12-11T13:23:37.513Z
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "IConnectPoint_Reservation")
@XmlSeeAlso({com.gzipcompressiontest.services.connectpoint_reservation.model.datacontract.ObjectFactory.class, com.gzipcompressiontest.services.connectpoint_reservation.model.microsoft.ObjectFactory.class, com.gzipcompressiontest.services.connectpoint_reservation.model.tempuri.ObjectFactory.class, com.gzipcompressiontest.services.connectpoint_reservation.model.datacontract6.ObjectFactory.class, com.gzipcompressiontest.services.connectpoint_reservation.model.microsoft1.ObjectFactory.class, com.gzipcompressiontest.services.connectpoint_reservation.model.datacontract5.ObjectFactory.class, com.gzipcompressiontest.services.connectpoint_reservation.model.datacontract2.ObjectFactory.class, com.gzipcompressiontest.services.connectpoint_reservation.model.datacontract1.ObjectFactory.class, com.gzipcompressiontest.services.connectpoint_reservation.model.datacontract4.ObjectFactory.class, com.gzipcompressiontest.services.connectpoint_reservation.model.datacontract3.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface IConnectPointReservation {

    @WebMethod(operationName = "ModifyPNR", action = "http://tempuri.org/IConnectPoint_Reservation/ModifyPNR")
    @Action(input = "http://tempuri.org/IConnectPoint_Reservation/ModifyPNR", output = "http://tempuri.org/IConnectPoint_Reservation/ModifyPNRResponse")
    @WebResult(name = "ModifyPNRResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
    public com.gzipcompressiontest.services.connectpoint_reservation.model.tempuri.ModifyPNRResponse modifyPNR(
        @WebParam(partName = "parameters", name = "ModifyPNR", targetNamespace = "http://tempuri.org/")
        com.gzipcompressiontest.services.connectpoint_reservation.model.tempuri.ModifyPNR parameters
    );

    @WebMethod(operationName = "EvaluateModificationOfPNR", action = "http://tempuri.org/IConnectPoint_Reservation/EvaluateModificationOfPNR")
    @Action(input = "http://tempuri.org/IConnectPoint_Reservation/EvaluateModificationOfPNR", output = "http://tempuri.org/IConnectPoint_Reservation/EvaluateModificationOfPNRResponse")
    @WebResult(name = "EvaluateModificationOfPNRResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
    public com.gzipcompressiontest.services.connectpoint_reservation.model.tempuri.EvaluateModificationOfPNRResponse evaluateModificationOfPNR(
        @WebParam(partName = "parameters", name = "EvaluateModificationOfPNR", targetNamespace = "http://tempuri.org/")
        com.gzipcompressiontest.services.connectpoint_reservation.model.tempuri.EvaluateModificationOfPNR parameters
    );

    /**
     * <summary>
     *  adds penalties based on supplied data.
     *  </summary>
     *  <param name="AddPenaltyRequest">header / detail info for penalties to add.</param>
     */
    @WebMethod(operationName = "AddPenalties", action = "http://tempuri.org/IConnectPoint_Reservation/AddPenalties")
    @Action(input = "http://tempuri.org/IConnectPoint_Reservation/AddPenalties", output = "http://tempuri.org/IConnectPoint_Reservation/AddPenaltiesResponse")
    @WebResult(name = "AddPenaltiesResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
    public com.gzipcompressiontest.services.connectpoint_reservation.model.tempuri.AddPenaltiesResponse addPenalties(
        @WebParam(partName = "parameters", name = "AddPenalties", targetNamespace = "http://tempuri.org/")
        com.gzipcompressiontest.services.connectpoint_reservation.model.tempuri.AddPenalties parameters
    );

    /**
     * <summary>
     *  adds taxes based on the given payload
     *  </summary>
     *  <param name="AddTaxRequest">header and detail data for the taxes to add.</param>
     */
    @WebMethod(operationName = "AddTaxes", action = "http://tempuri.org/IConnectPoint_Reservation/AddTaxes")
    @Action(input = "http://tempuri.org/IConnectPoint_Reservation/AddTaxes", output = "http://tempuri.org/IConnectPoint_Reservation/AddTaxesResponse")
    @WebResult(name = "AddTaxesResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
    public com.gzipcompressiontest.services.connectpoint_reservation.model.tempuri.AddTaxesResponse addTaxes(
        @WebParam(partName = "parameters", name = "AddTaxes", targetNamespace = "http://tempuri.org/")
        com.gzipcompressiontest.services.connectpoint_reservation.model.tempuri.AddTaxes parameters
    );

    @WebMethod(operationName = "OverrideReservationCharges", action = "http://tempuri.org/IConnectPoint_Reservation/OverrideReservationCharges")
    @Action(input = "http://tempuri.org/IConnectPoint_Reservation/OverrideReservationCharges", output = "http://tempuri.org/IConnectPoint_Reservation/OverrideReservationChargesResponse")
    @WebResult(name = "OverrideReservationChargesResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
    public com.gzipcompressiontest.services.connectpoint_reservation.model.tempuri.OverrideReservationChargesResponse overrideReservationCharges(
        @WebParam(partName = "parameters", name = "OverrideReservationCharges", targetNamespace = "http://tempuri.org/")
        com.gzipcompressiontest.services.connectpoint_reservation.model.tempuri.OverrideReservationCharges parameters
    );

    @WebMethod(operationName = "CreatePNRExt", action = "http://tempuri.org/IConnectPoint_Reservation/CreatePNRExt")
    @Action(input = "http://tempuri.org/IConnectPoint_Reservation/CreatePNRExt", output = "http://tempuri.org/IConnectPoint_Reservation/CreatePNRExtResponse")
    @WebResult(name = "CreatePNRExtResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
    public com.gzipcompressiontest.services.connectpoint_reservation.model.tempuri.CreatePNRExtResponse createPNRExt(
        @WebParam(partName = "parameters", name = "CreatePNRExt", targetNamespace = "http://tempuri.org/")
        com.gzipcompressiontest.services.connectpoint_reservation.model.tempuri.CreatePNRExt parameters
    );

    @WebMethod(operationName = "CancelPNRFFPAllTaxes", action = "http://tempuri.org/IConnectPoint_Reservation/CancelPNRFFPAllTaxes")
    @Action(input = "http://tempuri.org/IConnectPoint_Reservation/CancelPNRFFPAllTaxes", output = "http://tempuri.org/IConnectPoint_Reservation/CancelPNRFFPAllTaxesResponse")
    @WebResult(name = "CancelPNRFFPAllTaxesResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
    public com.gzipcompressiontest.services.connectpoint_reservation.model.tempuri.CancelPNRFFPAllTaxesResponse cancelPNRFFPAllTaxes(
        @WebParam(partName = "parameters", name = "CancelPNRFFPAllTaxes", targetNamespace = "http://tempuri.org/")
        com.gzipcompressiontest.services.connectpoint_reservation.model.tempuri.CancelPNRFFPAllTaxes parameters
    );

    @WebMethod(operationName = "RetrievePNR", action = "http://tempuri.org/IConnectPoint_Reservation/RetrievePNR")
    @Action(input = "http://tempuri.org/IConnectPoint_Reservation/RetrievePNR", output = "http://tempuri.org/IConnectPoint_Reservation/RetrievePNRResponse")
    @WebResult(name = "RetrievePNRResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
    public com.gzipcompressiontest.services.connectpoint_reservation.model.tempuri.RetrievePNRResponse retrievePNR(
        @WebParam(partName = "parameters", name = "RetrievePNR", targetNamespace = "http://tempuri.org/")
        com.gzipcompressiontest.services.connectpoint_reservation.model.tempuri.RetrievePNR parameters
    );

    @WebMethod(operationName = "GetReservation", action = "http://tempuri.org/IConnectPoint_Reservation/GetReservation")
    @Action(input = "http://tempuri.org/IConnectPoint_Reservation/GetReservation", output = "http://tempuri.org/IConnectPoint_Reservation/GetReservationResponse")
    @WebResult(name = "GetReservationResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
    public com.gzipcompressiontest.services.connectpoint_reservation.model.tempuri.GetReservationResponse getReservation(
        @WebParam(partName = "parameters", name = "GetReservation", targetNamespace = "http://tempuri.org/")
        com.gzipcompressiontest.services.connectpoint_reservation.model.tempuri.GetReservation parameters
    );

    @WebMethod(operationName = "GetApisInfo", action = "http://tempuri.org/IConnectPoint_Reservation/GetApisInfo")
    @Action(input = "http://tempuri.org/IConnectPoint_Reservation/GetApisInfo", output = "http://tempuri.org/IConnectPoint_Reservation/GetApisInfoResponse")
    @WebResult(name = "GetApisInfoResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
    public com.gzipcompressiontest.services.connectpoint_reservation.model.tempuri.GetApisInfoResponse getApisInfo(
        @WebParam(partName = "parameters", name = "GetApisInfo", targetNamespace = "http://tempuri.org/")
        com.gzipcompressiontest.services.connectpoint_reservation.model.tempuri.GetApisInfo parameters
    );

    @WebMethod(operationName = "CreatePNRFFP", action = "http://tempuri.org/IConnectPoint_Reservation/CreatePNRFFP")
    @Action(input = "http://tempuri.org/IConnectPoint_Reservation/CreatePNRFFP", output = "http://tempuri.org/IConnectPoint_Reservation/CreatePNRFFPResponse")
    @WebResult(name = "CreatePNRFFPResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
    public com.gzipcompressiontest.services.connectpoint_reservation.model.tempuri.CreatePNRFFPResponse createPNRFFP(
        @WebParam(partName = "parameters", name = "CreatePNRFFP", targetNamespace = "http://tempuri.org/")
        com.gzipcompressiontest.services.connectpoint_reservation.model.tempuri.CreatePNRFFP parameters
    );

    @WebMethod(operationName = "ModifyPNRFFP", action = "http://tempuri.org/IConnectPoint_Reservation/ModifyPNRFFP")
    @Action(input = "http://tempuri.org/IConnectPoint_Reservation/ModifyPNRFFP", output = "http://tempuri.org/IConnectPoint_Reservation/ModifyPNRFFPResponse")
    @WebResult(name = "ModifyPNRFFPResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
    public com.gzipcompressiontest.services.connectpoint_reservation.model.tempuri.ModifyPNRFFPResponse modifyPNRFFP(
        @WebParam(partName = "parameters", name = "ModifyPNRFFP", targetNamespace = "http://tempuri.org/")
        com.gzipcompressiontest.services.connectpoint_reservation.model.tempuri.ModifyPNRFFP parameters
    );

    @WebMethod(operationName = "CancelPNRFFP", action = "http://tempuri.org/IConnectPoint_Reservation/CancelPNRFFP")
    @Action(input = "http://tempuri.org/IConnectPoint_Reservation/CancelPNRFFP", output = "http://tempuri.org/IConnectPoint_Reservation/CancelPNRFFPResponse")
    @WebResult(name = "CancelPNRFFPResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
    public com.gzipcompressiontest.services.connectpoint_reservation.model.tempuri.CancelPNRFFPResponse cancelPNRFFP(
        @WebParam(partName = "parameters", name = "CancelPNRFFP", targetNamespace = "http://tempuri.org/")
        com.gzipcompressiontest.services.connectpoint_reservation.model.tempuri.CancelPNRFFP parameters
    );

    @WebMethod(operationName = "SummaryPNR", action = "http://tempuri.org/IConnectPoint_Reservation/SummaryPNR")
    @Action(input = "http://tempuri.org/IConnectPoint_Reservation/SummaryPNR", output = "http://tempuri.org/IConnectPoint_Reservation/SummaryPNRResponse")
    @WebResult(name = "SummaryPNRResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
    public com.gzipcompressiontest.services.connectpoint_reservation.model.tempuri.SummaryPNRResponse summaryPNR(
        @WebParam(partName = "parameters", name = "SummaryPNR", targetNamespace = "http://tempuri.org/")
        com.gzipcompressiontest.services.connectpoint_reservation.model.tempuri.SummaryPNR parameters
    );

    @WebMethod(operationName = "HoldInventory", action = "http://tempuri.org/IConnectPoint_Reservation/HoldInventory")
    @Action(input = "http://tempuri.org/IConnectPoint_Reservation/HoldInventory", output = "http://tempuri.org/IConnectPoint_Reservation/HoldInventoryResponse")
    @WebResult(name = "HoldInventoryResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
    public com.gzipcompressiontest.services.connectpoint_reservation.model.tempuri.HoldInventoryResponse holdInventory(
        @WebParam(partName = "parameters", name = "HoldInventory", targetNamespace = "http://tempuri.org/")
        com.gzipcompressiontest.services.connectpoint_reservation.model.tempuri.HoldInventory parameters
    );

    @WebMethod(operationName = "GetReservationBalance", action = "http://tempuri.org/IConnectPoint_Reservation/GetReservationBalance")
    @Action(input = "http://tempuri.org/IConnectPoint_Reservation/GetReservationBalance", output = "http://tempuri.org/IConnectPoint_Reservation/GetReservationBalanceResponse")
    @WebResult(name = "GetReservationBalanceResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
    public com.gzipcompressiontest.services.connectpoint_reservation.model.tempuri.GetReservationBalanceResponse getReservationBalance(
        @WebParam(partName = "parameters", name = "GetReservationBalance", targetNamespace = "http://tempuri.org/")
        com.gzipcompressiontest.services.connectpoint_reservation.model.tempuri.GetReservationBalance parameters
    );

    @WebMethod(operationName = "HistoryPNR", action = "http://tempuri.org/IConnectPoint_Reservation/HistoryPNR")
    @Action(input = "http://tempuri.org/IConnectPoint_Reservation/HistoryPNR", output = "http://tempuri.org/IConnectPoint_Reservation/HistoryPNRResponse")
    @WebResult(name = "HistoryPNRResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
    public com.gzipcompressiontest.services.connectpoint_reservation.model.tempuri.HistoryPNRResponse historyPNR(
        @WebParam(partName = "parameters", name = "HistoryPNR", targetNamespace = "http://tempuri.org/")
        com.gzipcompressiontest.services.connectpoint_reservation.model.tempuri.HistoryPNR parameters
    );

    @WebMethod(operationName = "SummaryPNRExt", action = "http://tempuri.org/IConnectPoint_Reservation/SummaryPNRExt")
    @Action(input = "http://tempuri.org/IConnectPoint_Reservation/SummaryPNRExt", output = "http://tempuri.org/IConnectPoint_Reservation/SummaryPNRExtResponse")
    @WebResult(name = "SummaryPNRExtResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
    public com.gzipcompressiontest.services.connectpoint_reservation.model.tempuri.SummaryPNRExtResponse summaryPNRExt(
        @WebParam(partName = "parameters", name = "SummaryPNRExt", targetNamespace = "http://tempuri.org/")
        com.gzipcompressiontest.services.connectpoint_reservation.model.tempuri.SummaryPNRExt parameters
    );

    /**
     * <summary>
     *   <para>CancelPNR allows for two actions to occur.</para>
     *   <para>If action CancelReservation is specified in the request object submitted then the reservation that is associated with the session will be cancelled within
     *  the Radxx System. The associated charges that are refundable will be refunded accordingly and any cancellation fees that maybe accessed will be applied</para>
     *   <para>If ActionType RevertReservation is specified then this action will rollback any Presaved mofications that may have occured in the in memory object. The end
     *  result will put the reservation back to the state that it was in upon initial call to RetrieveReservation.</para>
     *  </summary>
     */
    @WebMethod(operationName = "CancelPNR", action = "http://tempuri.org/IConnectPoint_Reservation/CancelPNR")
    @Action(input = "http://tempuri.org/IConnectPoint_Reservation/CancelPNR", output = "http://tempuri.org/IConnectPoint_Reservation/CancelPNRResponse")
    @WebResult(name = "CancelPNRResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
    public com.gzipcompressiontest.services.connectpoint_reservation.model.tempuri.CancelPNRResponse cancelPNR(
        @WebParam(partName = "parameters", name = "CancelPNR", targetNamespace = "http://tempuri.org/")
        com.gzipcompressiontest.services.connectpoint_reservation.model.tempuri.CancelPNR parameters
    );

    @WebMethod(operationName = "ReleaseInventory", action = "http://tempuri.org/IConnectPoint_Reservation/ReleaseInventory")
    @Action(input = "http://tempuri.org/IConnectPoint_Reservation/ReleaseInventory", output = "http://tempuri.org/IConnectPoint_Reservation/ReleaseInventoryResponse")
    @WebResult(name = "ReleaseInventoryResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
    public com.gzipcompressiontest.services.connectpoint_reservation.model.tempuri.ReleaseInventoryResponse releaseInventory(
        @WebParam(partName = "parameters", name = "ReleaseInventory", targetNamespace = "http://tempuri.org/")
        com.gzipcompressiontest.services.connectpoint_reservation.model.tempuri.ReleaseInventory parameters
    );

    /**
     * <summary>
     *  Create Group PNR
     *  <Date>10-Aug-2016</Date>
     *  </summary>
     *  <param name="CreatePnrRequest">{{Global.Radixx.ConnectPoint.Reservation.Request.CreatePNR}}</param>
     *  <returns>{{Global.Radixx.ConnectPoint.Reservation.Response.ViewPNR}}</returns>
     */
    @WebMethod(operationName = "OverBook", action = "http://tempuri.org/IConnectPoint_Reservation/OverBook")
    @Action(input = "http://tempuri.org/IConnectPoint_Reservation/OverBook", output = "http://tempuri.org/IConnectPoint_Reservation/OverBookResponse")
    @WebResult(name = "OverBookResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
    public com.gzipcompressiontest.services.connectpoint_reservation.model.tempuri.OverBookResponse overBook(
        @WebParam(partName = "parameters", name = "OverBook", targetNamespace = "http://tempuri.org/")
        com.gzipcompressiontest.services.connectpoint_reservation.model.tempuri.OverBook parameters
    );

    @WebMethod(operationName = "SetApisInfo", action = "http://tempuri.org/IConnectPoint_Reservation/SetApisInfo")
    @Action(input = "http://tempuri.org/IConnectPoint_Reservation/SetApisInfo", output = "http://tempuri.org/IConnectPoint_Reservation/SetApisInfoResponse")
    @WebResult(name = "SetApisInfoResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
    public com.gzipcompressiontest.services.connectpoint_reservation.model.tempuri.SetApisInfoResponse setApisInfo(
        @WebParam(partName = "parameters", name = "SetApisInfo", targetNamespace = "http://tempuri.org/")
        com.gzipcompressiontest.services.connectpoint_reservation.model.tempuri.SetApisInfo parameters
    );

    @WebMethod(operationName = "CreatePNR", action = "http://tempuri.org/IConnectPoint_Reservation/CreatePNR")
    @Action(input = "http://tempuri.org/IConnectPoint_Reservation/CreatePNR", output = "http://tempuri.org/IConnectPoint_Reservation/CreatePNRResponse")
    @WebResult(name = "CreatePNRResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
    public com.gzipcompressiontest.services.connectpoint_reservation.model.tempuri.CreatePNRResponse createPNR(
        @WebParam(partName = "parameters", name = "CreatePNR", targetNamespace = "http://tempuri.org/")
        com.gzipcompressiontest.services.connectpoint_reservation.model.tempuri.CreatePNR parameters
    );

    @WebMethod(operationName = "CancelPNRFFPAutoCancel", action = "http://tempuri.org/IConnectPoint_Reservation/CancelPNRFFPAutoCancel")
    @Action(input = "http://tempuri.org/IConnectPoint_Reservation/CancelPNRFFPAutoCancel", output = "http://tempuri.org/IConnectPoint_Reservation/CancelPNRFFPAutoCancelResponse")
    @WebResult(name = "CancelPNRFFPAutoCancelResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
    public com.gzipcompressiontest.services.connectpoint_reservation.model.tempuri.CancelPNRFFPAutoCancelResponse cancelPNRFFPAutoCancel(
        @WebParam(partName = "parameters", name = "CancelPNRFFPAutoCancel", targetNamespace = "http://tempuri.org/")
        com.gzipcompressiontest.services.connectpoint_reservation.model.tempuri.CancelPNRFFPAutoCancel parameters
    );

    @WebMethod(operationName = "ImportPNR", action = "http://tempuri.org/IConnectPoint_Reservation/ImportPNR")
    @Action(input = "http://tempuri.org/IConnectPoint_Reservation/ImportPNR", output = "http://tempuri.org/IConnectPoint_Reservation/ImportPNRResponse")
    @WebResult(name = "ImportPNRResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
    public com.gzipcompressiontest.services.connectpoint_reservation.model.tempuri.ImportPNRResponse importPNR(
        @WebParam(partName = "parameters", name = "ImportPNR", targetNamespace = "http://tempuri.org/")
        com.gzipcompressiontest.services.connectpoint_reservation.model.tempuri.ImportPNR parameters
    );
}
