/**
 * This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.
 */
package com.sample11.services.thom.controller;

import com.sample11.services.thom.services.ThomService;
import com.sample11.services.thom.GetBankType;
import java.lang.String;
import com.sample11.services.thom.GetBankResponseType;
import org.springframework.web.bind.annotation.*;
import org.springframework.http.MediaType;
import org.springframework.beans.factory.annotation.Autowired;

@RestController
@RequestMapping(value = "/thom")
public class ThomController {

    @Autowired
    private ThomService thomService;

    @RequestMapping(value = "/bank", method = RequestMethod.GET)
    public GetBankResponseType getBank(@RequestParam(value = "blz", required = true) String blz) {
        GetBankType parameters = new GetBankType();
        parameters.setBlz(blz);
        return thomService.getBank(parameters);
    }
}
